# Generated by Django 3.2 on 2022-12-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20221219_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hook_text',
            new_name='price',
        ),
        migrations.DeleteModel(
            name='ReComment',
        ),
    ]
